# Site settings
title: End try
author: prongbang
email: prongbang@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  ~บล็อคของคนแบบนี้ไง~
baseurl: ""
url: "https://prongbang.github.io"

# Social links
twitter_username: prongbang
github_username:  prongbang

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - octopress-autoprefixer
  - jekyll-paginate-v2
  # - jekyll-paginate

# Produces a cleaner folder structure when using categories
permalink: /:categories/:year/:month/:title.html

pagination:
  enabled: true
  per_page: 15
  permalink: '/blog/page/:num/'
  title: ':title - page :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

# Explicitly turn off the old code
# Pagination Settings
# paginate: 1
# paginate_path: "/blog/page/:num/"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
